// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANUxR9CkPkRS1LJFfv92gVWssvkUuFxjs',
    appId: '1:753826641492:web:585cc77b366979f7a25fc1',
    messagingSenderId: '753826641492',
    projectId: 'bsocialp',
    authDomain: 'bsocialp.firebaseapp.com',
    storageBucket: 'bsocialp.appspot.com',
    measurementId: 'G-F06LFWW30W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNU4hDLJnu4AnDY_9R5OVeJpL_izckYnA',
    appId: '1:753826641492:android:abea7295963a275ca25fc1',
    messagingSenderId: '753826641492',
    projectId: 'bsocialp',
    storageBucket: 'bsocialp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0I7zUPIc1yRJTbCbeeh5owsUgrDsg83w',
    appId: '1:753826641492:ios:9d01f7e9f0aa3f65a25fc1',
    messagingSenderId: '753826641492',
    projectId: 'bsocialp',
    storageBucket: 'bsocialp.appspot.com',
    iosClientId: '753826641492-qh2n9ph68aifhcjt6udh59pea1h0utah.apps.googleusercontent.com',
    iosBundleId: 'com.blake.social',
  );
}
